export const TOMATO_APP_MESSAGE_EDITING_STARTED = 'TOMATO_APP_MESSAGE_EDITING_STARTED';
export const TOMATO_APP_MESSAGE_EDITING_CANCELLED = 'TOMATO_APP_MESSAGE_EDITING_CANCELLED';
export const TOMATO_APP_MESSAGE_EDITING_SUCCESS = 'TOMATO_APP_MESSAGE_EDITING_SUCCESS';

export const TOMATO_APP_LOADING_STARTED = 'TOMATO_APP_LOADING_STARTED';
export const TOMATO_APP_LOADING_SUCCESS = 'TOMATO_APP_LOADING_SUCCESS';

export const TOMATO_APP_USER_LOGIN_STARTED = 'TOMATO_APP_USER_LOGIN_STARTED ';
export const TOMATO_APP_USER_LOGIN_SUCCESS = 'TOMATO_APP_USER_LOGIN_SUCCESS';
export const TOMATO_APP_USER_LOGIN_FAILED = 'TOMATO_APP_USER_LOGIN_FAILED';

export const TOMATO_APP_MESSAGE_CREATE_STARTED = 'TOMATO_APP_MESSAGE_CREATE_STARTED';
export const TOMATO_APP_MESSAGE_CREATE_IN_PROGRESS = 'TOMATO_APP_MESSAGE_CREATE_IN_PROGRESS';
export const TOMATO_APP_MESSAGE_CREATE_SUCCESS = 'TOMATO_APP_MESSAGE_CREATE_SUCCESS';

export const TOMATO_APP_MESSAGE_DELETE_COMPLETE_STARTED = 'TOMATO_APP_MESSAGE_DELETE_COMPLETE_STARTED';
export const TOMATO_APP_MESSAGE_DELETE_COMPLETE_SUCCESS = 'TOMATO_APP_MESSAGE_DELETE_COMPLETE_SUCCESS';
