export const TOMATO_APP_MESSAGE_EDITING_STARTED = 'TOMATO_APP_MESSAGE_EDITING_STARTED';
export const TOMATO_APP_MESSAGE_EDITING_CANCELLED = 'TOMATO_APP_MESSAGE_EDITING_CANCELLED';
export const TOMATO_APP_MESSAGE_EDITING_SUCCESS = 'TOMATO_APP_MESSAGE_EDITING_SUCCESS';

export const TOMATO_APP_CHANNEL_EDITING_STARTED = 'TOMATO_APP_CHANNEL_EDITING_STARTED';
export const TOMATO_APP_CHANNEL_EDITING_CANCELLED = 'TOMATO_APP_CHANNEL_EDITING_CANCELLED';
export const TOMATO_APP_CHANNEL_EDITING_SUCCESS = 'TOMATO_APP_CHANNEL_EDITING_SUCCESS';

export const TOMATO_APP_LOADING_STARTED = 'TOMATO_APP_LOADING_STARTED';
export const TOMATO_APP_LOADING_USERS_STARTED = 'TOMATO_APP_LOADING_USERS_STARTED';
export const TOMATO_APP_LOADING_CHANNELS_STARTED = 'TOMATO_APP_LOADING_CHANNELS_STARTED';
export const TOMATO_APP_LOADING_MESSAGES_STARTED = 'TOMATO_APP_LOADING_MESSAGES_STARTED';
export const TOMATO_APP_LOADING_SUCCESS = 'TOMATO_APP_LOADING_SUCCESS';
export const TOMATO_APP_LOADING_USERS_SUCCESS = 'TOMATO_APP_LOADING_USERS_SUCCESS';
export const TOMATO_APP_LOADING_CHANNELS_SUCCESS = 'TOMATO_APP_LOADING_CHANNELS_SUCCESS';
export const TOMATO_APP_LOADING_MESSAGES_SUCCESS = 'TOMATO_APP_LOADING_MESSAGES_SUCCESS';

export const TOMATO_APP_USER_LOGIN_STARTED = 'TOMATO_APP_USER_LOGIN_STARTED ';
export const TOMATO_APP_USER_LOGIN_SUCCESS = 'TOMATO_APP_USER_LOGIN_SUCCESS';
export const TOMATO_APP_USER_LOGIN_FAILED = 'TOMATO_APP_USER_LOGIN_FAILED';

export const TOMATO_APP_AUTHENTICATION_TOKEN_RECEIVED = 'TOMATO_APP_AUTHENTICATION_TOKEN_RECEIVED';

export const TOMATO_APP_USER_CHANNELS_STARTED = 'TOMATO_APP_USER_CHANNELS_STARTED';
export const TOMATO_APP_USER_CHANNELS_SUCCESS = 'TOMATO_APP_USER_CHANNELS_SUCCESS';
export const TOMATO_APP_USER_CHANNELS_FAILED = 'TOMATO_APP_USER_CHANNELS_FAILED';


export const TOMATO_APP_USER_REGISTER_STARTED = 'TOMATO_APP_USER_REGISTER_STARTED ';
export const TOMATO_APP_USER_REGISTER_SUCCESS = 'TOMATO_APP_USER_REGISTER_SUCCESS';
export const TOMATO_APP_USER_REGISTER_FAILED = 'TOMATO_APP_USER_REGISTER_FAILED';

export const TOMATO_APP_MESSAGE_CREATE_STARTED = 'TOMATO_APP_MESSAGE_CREATE_STARTED';
export const TOMATO_APP_MESSAGE_CREATE_IN_PROGRESS = 'TOMATO_APP_MESSAGE_CREATE_IN_PROGRESS';
export const TOMATO_APP_MESSAGE_CREATE_SUCCESS = 'TOMATO_APP_MESSAGE_CREATE_SUCCESS';

export const TOMATO_APP_CHANNEL_CREATE_STARTED = 'TOMATO_APP_CHANNEL_CREATE_STARTED';
export const TOMATO_APP_CHANNEL_CREATE_IN_PROGRESS = 'TOMATO_APP_CHANNEL_CREATE_IN_PROGRESS';
export const TOMATO_APP_CHANNEL_CREATE_SUCCESS = 'TOMATO_APP_CHANNEL_CREATE_SUCCESS';
export const TOMATO_APP_CHANNEL_ORDER_CHANGED = 'TOMATO_APP_CHANNEL_ORDER_CHANGED';
export const TOMATO_APP_CHANNEL_ORDER_STARTED = 'TOMATO_APP_CHANNEL_ORDER_STARTED';

export const TOMATO_APP_MESSAGE_DELETE_COMPLETE_STARTED = 'TOMATO_APP_MESSAGE_DELETE_COMPLETE_STARTED';
export const TOMATO_APP_MESSAGE_DELETE_COMPLETE_SUCCESS = 'TOMATO_APP_MESSAGE_DELETE_COMPLETE_SUCCESS';

export const TOMATO_APP_CHANNEL_DELETE_COMPLETE_STARTED = 'TOMATO_APP_CHANNEL_DELETE_COMPLETE_STARTED';
export const TOMATO_APP_CHANNEL_DELETE_COMPLETE_SUCCESS = 'TOMATO_APP_CHANNEL_DELETE_COMPLETE_SUCCESS';
